// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdCKwsyCWXf7P2xwx2BouPJEplYmRWRUA',
    appId: '1:1068419854660:web:55de86f8591d1c3feee711',
    messagingSenderId: '1068419854660',
    projectId: 'e-commerce-95cd8',
    authDomain: 'e-commerce-95cd8.firebaseapp.com',
    storageBucket: 'e-commerce-95cd8.firebasestorage.app',
    measurementId: 'G-NM0C9DKZZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHooPOG1GLxHPkND7tD40uYVpau7DXy7I',
    appId: '1:1068419854660:android:26ca6e884db5985beee711',
    messagingSenderId: '1068419854660',
    projectId: 'e-commerce-95cd8',
    storageBucket: 'e-commerce-95cd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9lPQXh-tq0M9-JC2eUCFUUg1upfkbrLg',
    appId: '1:1068419854660:ios:51b14e53f11985c6eee711',
    messagingSenderId: '1068419854660',
    projectId: 'e-commerce-95cd8',
    storageBucket: 'e-commerce-95cd8.firebasestorage.app',
    iosBundleId: 'com.example.untitled12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9lPQXh-tq0M9-JC2eUCFUUg1upfkbrLg',
    appId: '1:1068419854660:ios:51b14e53f11985c6eee711',
    messagingSenderId: '1068419854660',
    projectId: 'e-commerce-95cd8',
    storageBucket: 'e-commerce-95cd8.firebasestorage.app',
    iosBundleId: 'com.example.untitled12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdCKwsyCWXf7P2xwx2BouPJEplYmRWRUA',
    appId: '1:1068419854660:web:9dbd21a675265f97eee711',
    messagingSenderId: '1068419854660',
    projectId: 'e-commerce-95cd8',
    authDomain: 'e-commerce-95cd8.firebaseapp.com',
    storageBucket: 'e-commerce-95cd8.firebasestorage.app',
    measurementId: 'G-BBE3H01BS6',
  );
}
